# Generated by Django 5.2 on 2025-04-20 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyInfo',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(null=True)),
                ('company_tag', models.CharField(null=True)),
                ('company_salary', models.CharField(null=True)),
                ('company_location', models.CharField(null=True)),
                ('company_headcount', models.CharField(null=True)),
                ('company_revenue', models.CharField(null=True)),
                ('company_info', models.CharField(null=True)),
                ('reg_dt', models.DateTimeField(auto_now_add=True)),
                ('mod_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='noticeInfo',
            fields=[
                ('notice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('notice_job_category', models.CharField(null=True)),
                ('notice_location', models.CharField(null=True)),
                ('notice_career', models.CharField(null=True)),
                ('notice_title', models.CharField(null=True)),
                ('notice_position', models.CharField(null=True)),
                ('notice_main_work', models.CharField(null=True)),
                ('notice_qualification', models.CharField(null=True)),
                ('notice_preferred_qualification', models.CharField(null=True)),
                ('notice_welfare', models.CharField(null=True)),
                ('notice_category', models.CharField(null=True)),
                ('notice_end_date', models.CharField(null=True)),
                ('notice_tech_stack', models.CharField(null=True)),
                ('notice_url', models.CharField(null=True)),
                ('reg_dt', models.DateTimeField(auto_now_add=True)),
                ('mod_dt', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='charts.companyinfo')),
            ],
        ),
    ]
