# Generated by Django 5.2 on 2025-04-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainWorkChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_id', models.IntegerField()),
                ('notice_main_work', models.TextField(db_column='main_work')),
                ('label', models.IntegerField()),
            ],
        ),
    ]
