# Generated by Django 5.2 on 2025-04-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredQualificationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_sentence', models.CharField(null=True)),
                ('frequency', models.IntegerField(null=True)),
                ('sentences', models.TextField(null=True)),
            ],
            options={
                'db_table': 'charts_preferred_qualificationinfo',
            },
        ),
    ]
